// Sample borrowing markets data
export const borrowingMarkets = [
  {
    name: "USDC",
    borrowRate: "11.2%",
    totalBorrowed: "$32.1M",
    liquidity: "$13.2M",
    liquidityPercentage: "29%",
    icon: "💲",
    collateralFactor: "85%",
    maxLTV: "80%",
  },
  {
    name: "ETH",
    borrowRate: "8.4%",
    totalBorrowed: "$18.5M",
    liquidity: "$10.2M",
    liquidityPercentage: "35%",
    icon: "🔷",
    collateralFactor: "75%",
    maxLTV: "70%",
  },
  {
    name: "BTC",
    borrowRate: "7.9%",
    totalBorrowed: "$24.6M",
    liquidity: "$7.5M",
    liquidityPercentage: "23%",
    icon: "🔶",
    collateralFactor: "70%",
    maxLTV: "65%",
  },
  {
    name: "DAI",
    borrowRate: "10.5%",
    totalBorrowed: "$14.3M",
    liquidity: "$4.6M",
    liquidityPercentage: "24%",
    icon: "🟡",
    collateralFactor: "85%",
    maxLTV: "80%",
  },
  {
    name: "LINK",
    borrowRate: "12.3%",
    totalBorrowed: "$8.1M",
    liquidity: "$4.2M",
    liquidityPercentage: "34%",
    icon: "🔗",
    collateralFactor: "65%",
    maxLTV: "60%",
  },
];

// Sample user borrowing positions
export const myBorrowingPositions = [
  {
    name: "ETH",
    borrowedAmount: "1.5",
    value: "$4,368.75",
    borrowRate: "8.4%",
    accrued: "$12.89",
    icon: "🔷",
    healthFactor: "1.82",
    collateral: "USDC",
    collateralAmount: "$8,000",
  },
  {
    name: "DAI",
    borrowedAmount: "3,200",
    value: "$3,206.40",
    borrowRate: "10.5%",
    accrued: "$9.73",
    icon: "🟡",
    healthFactor: "2.14",
    collateral: "ETH",
    collateralAmount: "2.35 ETH ($6,862.50)",
  },
];
